
import java.io.*;
import common.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import ocsf.server.ConnectionToClient;

public class GameClientGUI extends javax.swing.JFrame implements GameIF {

    final public static int DEFAULT_PORT = 5555;
    GameClient client;
    static GameClientGUI gameCli;
    private boolean isClientTurn = false;
    DefaultListModel listModel = new DefaultListModel();

    // Creates new form GameClientGUI
    public GameClientGUI() {
        initComponents();
    }

    public void startClient(String ID, String host, int port) {
        try {
            client = new GameClient(ID, host, port, this);
            if (radioButtonFirst.isSelected()) {
                client.sendToServer("#clientFirst");
                receiveCommand("#clientTurn");
            } //else client.sendToServer("#clientSecond");
        } catch (IOException exception) {
            System.out.println("Error: Can't setup connection!"
                    + " Awaiting command");
            //System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        connectButton = new javax.swing.JButton();
        hostTextField = new javax.swing.JTextField();
        portTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        radioButtonFirst = new javax.swing.JRadioButton();
        radioButtonSecond = new javax.swing.JRadioButton();
        buttonGetGameList = new javax.swing.JButton();
        buttonCreateGame = new javax.swing.JButton();
        gameListBox = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButtonJoinGame = new javax.swing.JRadioButton();
        jRadioButtonCreateGame = new javax.swing.JRadioButton();
        jTextFieldGameSelect = new javax.swing.JTextField();
        buttonJoinGame = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");

        connectButton.setText("Connect to server");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        hostTextField.setText("localhost");

        portTextField.setText("5555");

        jLabel1.setText("Host");

        jLabel2.setText("Port");

        jLabel3.setText("ID");

        IDTextField.setText("obama");

        button1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        button1.setEnabled(false);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        button2.setEnabled(false);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        button3.setEnabled(false);
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        button4.setEnabled(false);
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        button5.setEnabled(false);
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        button6.setEnabled(false);
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        button7.setEnabled(false);
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        button8.setEnabled(false);
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        button9.setEnabled(false);
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButtonFirst);
        radioButtonFirst.setSelected(true);
        radioButtonFirst.setText("Go first");

        buttonGroup1.add(radioButtonSecond);
        radioButtonSecond.setText("Go second");

        buttonGetGameList.setText("Get game list");
        buttonGetGameList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGetGameListActionPerformed(evt);
            }
        });

        buttonCreateGame.setText("Create game");
        buttonCreateGame.setEnabled(false);
        buttonCreateGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateGameActionPerformed(evt);
            }
        });

        jList1.setModel(listModel);
        gameListBox.setViewportView(jList1);

        buttonGroup2.add(jRadioButtonJoinGame);
        jRadioButtonJoinGame.setSelected(true);
        jRadioButtonJoinGame.setText("Join game");
        jRadioButtonJoinGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJoinGameActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonCreateGame);
        jRadioButtonCreateGame.setText("Create game");
        jRadioButtonCreateGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCreateGameActionPerformed(evt);
            }
        });

        buttonJoinGame.setText("Join Game");
        buttonJoinGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJoinGameActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter game ID to join:");

        jLabel5.setText("ID");

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(connectButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioButtonFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButtonSecond))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(portTextField)
                            .addComponent(hostTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonGetGameList)
                                    .addComponent(buttonJoinGame)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gameListBox, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldGameSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buttonCreateGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonCreateGame)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonJoinGame)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(hostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jRadioButtonJoinGame)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameListBox, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonGetGameList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioButtonFirst)
                            .addComponent(radioButtonSecond))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(button2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonJoinGame)
                            .addComponent(jTextFieldGameSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButtonCreateGame))
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(button8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonCreateGame, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectButton)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        Thread t = new Thread(new Runnable() {
            public void run() {
                String host = "";
                int port = 0;  //The port number
                String ID = "";

                try {
                    ID = IDTextField.getText();
                } catch (Exception e) {
                    System.out.println("ERROR - No login ID specified. Connection aborted. Terminating client.");
                    System.exit(1);
                }
                try {
                    host = hostTextField.getText();
                } catch (Exception e) {
                    host = "localhost";
                }

                try {
                    port = Integer.parseInt(portTextField.getText());
                } catch (Exception e) {
                    port = DEFAULT_PORT;
                }
                startClient(ID, host, port);
                //GameClient chat = new GameClient(ID, host, port);
                //chat.accept();  //Wait for console data
            }
        });
        t.start();
    }//GEN-LAST:event_connectButtonActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        if (isClientTurn) {
            button2.setText("O");
            button2.setEnabled(false);
            client.handleMessageFromClientUI("#2");
            isClientTurn = false;
            statusLabel.setText("Server's turn");
        } else {
            JOptionPane.showMessageDialog(null, "Not your turn!");
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        if (isClientTurn) {
            button1.setText("O");
            button1.setEnabled(false);
            client.handleMessageFromClientUI("#1");
            isClientTurn = false;
            statusLabel.setText("Server's turn");
        } else {
            JOptionPane.showMessageDialog(null, "Not your turn!");
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        if (isClientTurn) {
            button3.setText("O");
            button3.setEnabled(false);
            client.handleMessageFromClientUI("#3");
            isClientTurn = false;
            statusLabel.setText("Server's turn");
        } else {
            JOptionPane.showMessageDialog(null, "Not your turn!");
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        if (isClientTurn) {
            button4.setText("O");
            button4.setEnabled(false);
            client.handleMessageFromClientUI("#4");
            isClientTurn = false;
            statusLabel.setText("Server's turn");
        } else {
            JOptionPane.showMessageDialog(null, "Not your turn!");
        }
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        if (isClientTurn) {
            button5.setText("O");
            button5.setEnabled(false);
            client.handleMessageFromClientUI("#5");
            isClientTurn = false;
            statusLabel.setText("Server's turn");
        } else {
            JOptionPane.showMessageDialog(null, "Not your turn!");
        }
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        if (isClientTurn) {
            button6.setText("O");
            button6.setEnabled(false);
            client.handleMessageFromClientUI("#6");
            isClientTurn = false;
            statusLabel.setText("Server's turn");
        } else {
            JOptionPane.showMessageDialog(null, "Not your turn!");
        }
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        if (isClientTurn) {
            button7.setText("O");
            button7.setEnabled(false);
            client.handleMessageFromClientUI("#7");
            isClientTurn = false;
            statusLabel.setText("Server's turn");
        } else {
            JOptionPane.showMessageDialog(null, "Not your turn!");
        }
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        if (isClientTurn) {
            button8.setText("O");
            button8.setEnabled(false);
            client.handleMessageFromClientUI("#8");
            isClientTurn = false;
            statusLabel.setText("Server's turn");
        } else {
            JOptionPane.showMessageDialog(null, "Not your turn!");
        }
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        if (isClientTurn) {
            button9.setText("O");
            button9.setEnabled(false);
            client.handleMessageFromClientUI("#9");
            isClientTurn = false;
            statusLabel.setText("Server's turn");
        } else {
            JOptionPane.showMessageDialog(null, "Not your turn!");
        }
    }//GEN-LAST:event_button9ActionPerformed

    private void buttonCreateGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateGameActionPerformed
        client.handleMessageFromClientUI("#createGame");
        buttonCreateGame.setEnabled(false);
    }//GEN-LAST:event_buttonCreateGameActionPerformed

    private void buttonGetGameListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGetGameListActionPerformed
        client.handleMessageFromClientUI("#getGameList");
    }//GEN-LAST:event_buttonGetGameListActionPerformed

    private void jRadioButtonJoinGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJoinGameActionPerformed
        buttonCreateGame.setEnabled(false);
        buttonGetGameList.setEnabled(true);
        buttonJoinGame.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonJoinGameActionPerformed

    private void jRadioButtonCreateGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCreateGameActionPerformed
        buttonCreateGame.setEnabled(true);
        buttonGetGameList.setEnabled(false);
        buttonJoinGame.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonCreateGameActionPerformed

    private void buttonJoinGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJoinGameActionPerformed
        String gameID = jTextFieldGameSelect.getText();
        try {
            client.sendToServer("#join " + gameID);
        } catch (IOException ex) {
            Logger.getLogger(GameClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonJoinGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gameCli = new GameClientGUI();
                gameCli.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTextField;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonCreateGame;
    private javax.swing.JButton buttonGetGameList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton buttonJoinGame;
    private javax.swing.JButton connectButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JScrollPane gameListBox;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextField hostTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JRadioButton jRadioButtonCreateGame;
    private javax.swing.JRadioButton jRadioButtonJoinGame;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldGameSelect;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField portTextField;
    private javax.swing.JRadioButton radioButtonFirst;
    private javax.swing.JRadioButton radioButtonSecond;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void display(String message) {
        System.out.println("> " + message);
    }

    public void accept() {
        try {
            BufferedReader fromConsole =
                    new BufferedReader(new InputStreamReader(System.in));
            String message;

            while (true) {
                message = fromConsole.readLine();
                client.handleMessageFromClientUI(message);
            }
        } catch (Exception ex) {
            System.out.println("Unexpected error while reading from console!" + ex);
        }
    }

    @Override
    public void receiveCommand(String command) {
        if (command.contains("#list")) {
            final String a = command.substring(5);
            Runnable temp = new Runnable() {
                public void run() {
                    //listModel.clear();
                    listModel.addElement(a);
                    revalidate();
                }
            };
            java.awt.EventQueue.invokeLater(temp);
        } else {
            switch (command) {
                case "enableAll": {
                    Runnable enable = new Runnable() {
                        public void run() {
                            button1.setEnabled(true);
                            button2.setEnabled(true);
                            button3.setEnabled(true);
                            button4.setEnabled(true);
                            button5.setEnabled(true);
                            button6.setEnabled(true);
                            button7.setEnabled(true);
                            button8.setEnabled(true);
                            button9.setEnabled(true);
                        }
                    };
                    java.awt.EventQueue.invokeLater(enable);
                    break;
                }
                case "disableAll": {
                    Runnable enable = new Runnable() {
                        public void run() {
                            button1.setEnabled(false);
                            button2.setEnabled(false);
                            button3.setEnabled(false);
                            button4.setEnabled(false);
                            button5.setEnabled(false);
                            button6.setEnabled(false);
                            button7.setEnabled(false);
                            button8.setEnabled(false);
                            button9.setEnabled(false);
                        }
                    };
                    java.awt.EventQueue.invokeLater(enable);
                    break;
                }
                case "#1": {
                    Runnable disable = new Runnable() {
                        public void run() {
                            button1.setText("X");
                            button1.setEnabled(false);
                        }
                    };
                    java.awt.EventQueue.invokeLater(disable);
                    break;
                }
                case "#2": {
                    Runnable disable = new Runnable() {
                        public void run() {
                            button2.setText("X");
                            button2.setEnabled(false);
                        }
                    };
                    java.awt.EventQueue.invokeLater(disable);
                    break;
                }
                case "#3": {
                    Runnable disable = new Runnable() {
                        public void run() {
                            button3.setText("X");
                            button3.setEnabled(false);
                        }
                    };
                    java.awt.EventQueue.invokeLater(disable);
                    break;
                }
                case "#4": {
                    Runnable disable = new Runnable() {
                        public void run() {
                            button4.setText("X");
                            button4.setEnabled(false);
                        }
                    };
                    java.awt.EventQueue.invokeLater(disable);
                    break;
                }
                case "#5": {
                    Runnable disable = new Runnable() {
                        public void run() {
                            button5.setText("X");
                            button5.setEnabled(false);
                        }
                    };
                    java.awt.EventQueue.invokeLater(disable);
                    break;
                }
                case "#6": {
                    Runnable disable = new Runnable() {
                        public void run() {
                            button6.setText("X");
                            button6.setEnabled(false);
                        }
                    };
                    java.awt.EventQueue.invokeLater(disable);
                    break;
                }
                case "#7": {
                    Runnable disable = new Runnable() {
                        public void run() {
                            button7.setText("X");
                            button7.setEnabled(false);
                        }
                    };
                    java.awt.EventQueue.invokeLater(disable);
                    break;
                }
                case "#8": {
                    Runnable disable = new Runnable() {
                        public void run() {
                            button8.setText("X");
                            button8.setEnabled(false);
                        }
                    };
                    java.awt.EventQueue.invokeLater(disable);
                    break;
                }
                case "#9": {
                    Runnable disable = new Runnable() {
                        public void run() {
                            button9.setText("X");
                            button9.setEnabled(false);
                        }
                    };
                    java.awt.EventQueue.invokeLater(disable);
                    break;
                }
                case "#serverWon": {
                    Runnable temp = new Runnable() {
                        public void run() {
                            statusLabel.setText("You lost...");
                        }
                    };
                    java.awt.EventQueue.invokeLater(temp);
                    break;
                }
                case "#clientWon": {
                    Runnable temp = new Runnable() {
                        public void run() {
                            statusLabel.setText("You won!");
                        }
                    };
                    java.awt.EventQueue.invokeLater(temp);
                    break;
                }
                case "#draw": {
                    Runnable temp = new Runnable() {
                        public void run() {
                            statusLabel.setText("Draw game!");
                        }
                    };
                    java.awt.EventQueue.invokeLater(temp);
                    break;
                }
                case "#clientTurn": {
                    Runnable temp = new Runnable() {
                        public void run() {
                            statusLabel.setText("Your turn!");
                            isClientTurn = true;
                        }
                    };
                    java.awt.EventQueue.invokeLater(temp);
                    break;
                }
                case "#restart":
                    receiveCommand("enableAll");
                    Runnable temp2 = new Runnable() {
                        public void run() {
                            button1.setText("");
                            button2.setText("");
                            button3.setText("");
                            button4.setText("");
                            button5.setText("");
                            button6.setText("");
                            button7.setText("");
                            button8.setText("");
                            button9.setText("");
                        }
                    };
                    java.awt.EventQueue.invokeLater(temp2);
                    break;
                case "#connected": {
                    Runnable temp3 = new Runnable() {
                        public void run() {
                            connectButton.setEnabled(false);
                        }
                    };
                    java.awt.EventQueue.invokeLater(temp3);
                    break;
                }
            }
        }

    }

    @Override
    public void addGame(int gameName, ConnectionToClient client) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void receiveList(DefaultListModel listModel) {
        this.listModel = listModel;
    }
}
